name: Create Release

on:
  push:
    tags:
      # Matches semantic versioning with optional 'v' prefix
      # Examples: v1.0.0, 1.0.0, v2.1.3-beta.1, 1.2.3-rc.2+build123
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.3

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Extract version from tag
        id: get_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          # Remove 'v' prefix if it exists
          VERSION=${TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Extract changelog for this version
        id: changelog
        run: |
          if [ -f CHANGELOG.md ]; then
            # Extract changelog section for this version
            awk '/^## \[?'${{ steps.get_version.outputs.VERSION }}'\]?/{flag=1; next} /^## \[?[0-9]/{flag=0} flag' CHANGELOG.md > release_notes.md
            if [ ! -s release_notes.md ]; then
              echo "No changelog entry found for version ${{ steps.get_version.outputs.VERSION }}" > release_notes.md
            fi
          else
            echo "Release v${{ steps.get_version.outputs.VERSION }}" > release_notes.md
            echo "" >> release_notes.md
            echo "This release includes updates and improvements to the n8n Notion Upload Media node." >> release_notes.md
          fi

      - name: Check if release exists
        id: check_release
        run: |
          if gh release view ${{ steps.get_version.outputs.TAG }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Release already exists for tag ${{ steps.get_version.outputs.TAG }}"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "No release found for tag ${{ steps.get_version.outputs.TAG }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        if: steps.check_release.outputs.exists != 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v${{ steps.get_version.outputs.VERSION }}
          body_path: release_notes.md
          draft: false
          prerelease: false

      - name: Get existing release upload URL
        id: get_release
        if: steps.check_release.outputs.exists == 'true'
        run: |
          UPLOAD_URL=$(gh api repos/${{ github.repository }}/releases/tags/${{ steps.get_version.outputs.TAG }} --jq .upload_url)
          echo "upload_url=$UPLOAD_URL" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create zip of dist folder
        run: |
          cd dist
          zip -r ../n8n-nodes-notion-upload-media-v${{ steps.get_version.outputs.VERSION }}-dist.zip .
          cd ..

      - name: Upload dist folder as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.check_release.outputs.exists == 'true' && steps.get_release.outputs.upload_url || steps.create_release.outputs.upload_url }}
          asset_path: ./n8n-nodes-notion-upload-media-v${{ steps.get_version.outputs.VERSION }}-dist.zip
          asset_name: n8n-nodes-notion-upload-media-v${{ steps.get_version.outputs.VERSION }}-dist.zip
          asset_content_type: application/zip
